
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.95.117:3306/order?characterEncoding=utf-8&useSSL=false

    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  context-path: /order
  port: 8003
